default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'user' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'password' } %>
  host:  <%= ENV.fetch("POSTGRES_HOST") { 'db' } %>

development:
  <<: *default
  database: user_service_development

test:
  <<: *default
  database: user_service_test

production:
  <<: *default
  database: user_service_production
  username: user_service
  password: <%= ENV["USER_SERVICE_DATABASE_PASSWORD"] %>
